<a href="https://colab.research.google.com/github/peisuke/ml-works/blob/main/1/1_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 1.2: 分類問題
- 目的
    - 機械学習の問題を解いてみる
- 内容
    - irisというデータセットを対象に、分類を実行

In [1]:
# プログラム内で使うツール群の宣言
import numpy as np
from sklearn import preprocessing
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, precision_score, recall_score
from sklearn import svm

In [2]:
# irisデータの読み込み
iris = load_iris()
features = preprocessing.minmax_scale(iris['data'])
labels = iris['target']

In [3]:
# 学習の入力データ（先頭の3つのみ表示）
print(features[:3])

[[0.22222222 0.625      0.06779661 0.04166667]
 [0.16666667 0.41666667 0.06779661 0.04166667]
 [0.11111111 0.5        0.05084746 0.04166667]]


In [4]:
# 予測すべき正解データ
print(labels[:3])

[0 0 0]


In [5]:
# データの分割
# 学習用のデータをtrain、テスト用のデータをtestとする
x_train, x_test, y_train, y_test = train_test_split(features, labels.ravel(), test_size=0.3)

In [6]:
# 学習の実行
# x_trainを入れた時に、y_trainが出力されるようなパラメータを学習
# ここではSuppor Vector Classificationという手法を利用する
clf = svm.SVC(kernel='rbf', C=3, gamma=0.1)
clf.fit(x_train, y_train)

SVC(C=3, gamma=0.1)

In [7]:
# 推論
# 学習したパラメータを利用して、テストデータ（x_test）に対して推論を実行
predict = clf.predict(x_test)

In [8]:
# テスト用データ
print(x_test[:3])

[[0.19444444 0.66666667 0.06779661 0.04166667]
 [0.61111111 0.41666667 0.76271186 0.70833333]
 [0.38888889 0.33333333 0.52542373 0.5       ]]


In [9]:
# テスト用データの正解
print(y_test[:3])

[0 2 1]


In [10]:
# 推論結果
print(predict[:3])

[0 2 1]


In [11]:
# 精度
# テストデータの正解と、推論結果を比較して正解率を計算
print(accuracy_score(y_test, predict))

0.9333333333333333
